### ISSUE TITLE
ddns-client wrongly changes sub-domain IP's

### ISSUE THREAD

**Issue by Paul-Reed** [LINKIWI/cloudflare-ddns-client#26] opened 2019-11-25 15:07 UTC
I have 3 servers, one local and 2 cloud servers.
The local uses the domain `myserver.com` and is running ddns-client.
The cloud servers use sub-domains of `myserver.com`;
`cloudone.myserver.com` & `cloudtwo.myserver.com`.

My `.cloudflare-ddns` config file is;
```
email=myemail@gmail.com
api_key=a5daf3b6c0if7f7dfsd6fsd9e56d7c2fb7c
domains=myserver.com
```

As both cloud servers using the sub-domain names have fixed IP addresses, I don't need ddns-client to update their IP's, but everytime ddns-client is run, it also updates one of the sub-domain IP addresses in Cloudflare to the IP address of my local server. The result is that one of my cloud servers cannot then be accessed, and I have to login to Cloudflare and manually change the IP back again to it's fixed IP address.

**Comment by Paul-Reed** [comment] 2019-11-30 09:44
@LINKIWI - Any thoughts Kevin?

**Comment by LINKIWI** [comment] 2019-11-30 15:50
I don't have time to address this right now, but I'm happy to merge a PR for this

**Comment by Paul-Reed** [comment] 2019-11-30 19:16
No worries Kevin, thanks for replying.

Unfortunately, although I have the time to address this, I don't have the skills (especially with Python), so I'll have to remove it from my system, and re-add it if/when you have time to fix.

Best wishes.

**Comment by zaanposni** [comment] 2020-03-02 18:34
Hey @Paul-Reed 

I tried to reproduce your issue. Are my dns records correct?
![grafik](https://user-images.githubusercontent.com/24491035/75705916-a29c9800-5cbc-11ea-8afe-9e4f3b7ecc1c.png)


My external IP is `.128`
I registered both dns records with `.129`, after using `cloudflare-ddns --update-now` the records get updated as you see in the picture. So I cannot really reproduce your issue right now :(

**Comment by Paul-Reed** [comment] 2020-03-02 19:06
> Are my dns records correct?

It's hard to tell from your screenshot. I have one domain which is being used on a local Rasp Pi, and 2 subdomains, each of which are used with fixed IP cloud VM servers.

So as I said in my first post;

> The local uses the domain myserver.com and is running ddns-client.
> The cloud servers use sub-domains of myserver.com;
> cloudone.myserver.com & cloudtwo.myserver.com.

From what I can see your config is different.

**Comment by zaanposni** [comment] 2020-03-04 09:12
<b>Start situation:</b>

Subdomain 
`test.myserver.com` is on a "static" ip `.129`.
My default domain
`myserver.com` is on my "old" ip `.129`.

![Unbenannt](https://user-images.githubusercontent.com/24491035/75862879-dfbd7300-5dff-11ea-9e9a-8ca071bc06b8.png)

Note: My new external ip is `.128`.
<b>New situation:</b>
After using `cloudflare-ddns --update-now`:

![Unbenannt](https://user-images.githubusercontent.com/24491035/75863114-417ddd00-5e00-11ea-809d-7495d84c672a.png)

My default domain `myserver.com` gets updated to the correct external ip.
My subdomain `test.myserver.com` is not updated.

As far as I understand, your issue is that your subdomain gets updated as well?
As you can see this is not the case.

Can you try again / try to describe your issue again?

**Comment by Paul-Reed** [comment] 2020-03-04 09:37
If you look at my first post;
myserver.com = 174.123.8.67 (dynamically assigned IP address)
cloudone.myserver.com = 40.47.45.18 (fixed ip address)
cloudtwo.myserver.com = 67.42.6.23 (fixed ip address)

ddns-client is installed on myserver.com
If myserver.com IP address changes to 15.168.88.5, then ddns-client updates cloudflare record to show myserver.com = 15.168.88.5 which is correct, BUT it also updates cloudone.myserver.com = 15.168.88.5 which is incorrect. Using the config shown in my post above, it should only update myserver.com

It's worth pointing out that I no longer have ddns-client installed, so can't test now.

**Comment by zaanposni** [comment] 2020-03-05 09:08
Well, I am pretty sure that I tested your exact situation and validated that the new DNS records are correct. So as long as you do not provide convincing information I do not see any issue here.
Otherwise, please explain where I made a mistake in setting up my test environment.

Moreover, saying that you cannot even test the CLI and still ignoring my positive test results is a bit arrogant, isn't it?

I suggest to close this issue @LINKIWI

**Comment by Paul-Reed** [comment] 2020-03-05 09:57
No need to be rude and make childish comments @zaanposni 
I said in my post above - 3 months ago that I have stopped using ddns-client (having written my own cloudflare updater instead).
I've explained very clearly what the issue was, and it's ridiculous to keep asking me if YOU are testing it correctly. If you don't know how to debug an issue, then leave it alone.

**Comment by LINKIWI** [comment] 2020-03-05 14:07
closing since this doesn't seem actionable

**Closed as completed by LINKIWI** 2020-03-05 14:07 UTC
