### ISSUE TITLE
Not asking for email address 

### ISSUE THREAD

**Issue by zozidalom** [LINKIWI/cloudflare-ddns-client#40] opened 2020-04-02 17:29 UTC
When I try to configure the software it is only asking for the API key and the domain(s) but it's not asking for the email address. Also, I do not see the API key in the config file, only the domains. Where is it stored?

Can you give me a sample for the config file so I can configure it manually and make it work?

![image](https://user-images.githubusercontent.com/24374345/78280053-c439ab00-7518-11ea-9899-740bec0b3dc5.png)

Thanks

**Comment by LINKIWI** [comment] 2020-04-03 01:49
@zaanposni Perhaps this is a regression related to #35?

**Comment by zaanposni** [comment] 2020-04-03 09:22
Hi @LINKIWI,

this issue is caused by a poorly spelled prompt.

In [Line81](https://github.com/LINKIWI/cloudflare-ddns-client/blob/master/cloudflare-ddns#L81) we are asking the user to specify whether he wants to use an apikey or token.
If something else than "[K]ey" or "[T]oken" is provided, the program does not handle this correctly.

However, @zozidalom provided his credentials there. I cannot really blame him, as the printed text is not very clear to be honest.

I can add a loop which will stick until the user says "[K]ey" or "[T]oken" and ignores anything else?
<hr/>
@zozidalom Here is a screenshot of the wanted dialog, I added an output of the file so you can create it locally until I provide a fix for this issue.

![grafik](https://user-images.githubusercontent.com/24491035/78344371-939b5500-759c-11ea-8b08-c10ac741357f.png)

**Comment by zozidalom** [comment] 2020-04-03 13:53
Thank you I was able to configure by putting the keys and values manually into the file.

**Comment by zaanposni** [comment] 2020-04-03 18:47
Hey, @zozidalom 
I fixed the dialog to be less confusing.
If you want, you can find the new version at master.
@LINKIWI Guess you can close this issue now.

**Comment by LINKIWI** [comment] 2020-04-04 20:33
Thanks!

**Closed as completed** 2020-04-04 20:33 UTC
